apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/argocd/base
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-dashboard
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/central-dashboard
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/cert-manager/base
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/certificates/base
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/istio
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  destination:
    namespace: istio-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: hub
        value: docker.io/istio
      - name: tag
        value: 1.10.1
    path: manifests/charts/istio-operator
    repoURL: https://github.com/istio/istio
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/istio-resources
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-web-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/jupyter-web-app
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katib
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/katib
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfserving
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/kfserving
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mpi-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/operators/mpi
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mxnet-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/operators/mxnet
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/namespace
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/notebook-controller
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/oidc-auth/overlays/keycloak
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/pipelines
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-defaults
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/pod-defaults
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile-controller
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/profile-controller_access-management
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/operators/pytorch
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roles
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/roles
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    helm:
      parameters:
      - name: cr.create
        value: "true"
      - name: commandArgs[0]
        value: --update-status
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorboards-controller
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/tensorboard-controller
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorboards-web-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/tensorboards-web-app
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorflow-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/operators/tensorflow
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volumes-web-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/notebooks/volumes-web-app
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xgboost-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v4.0.5
    path: distribution/kubeflow/operators/xgboost
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
